# Generated by Django 3.2.9 on 2021-12-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='feature',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeaturesValidators',
        ),
    ]
