# Generated by Django 2.2.20 on 2021-08-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cargo_coils_corbs_and_lines_feeders_fishing_accessories_groundbaits_ozzles_hooks_leashes_rods_soft_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='coils',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='corbs_and_lines',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='feeders',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='fishing_accessories',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='groundbaits_ozzles',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='hooks',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='leashes',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='rods',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='soft_baits',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='spinners',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='wobblers',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
    ]
