# Generated by Django 2.2.20 on 2021-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_soft_baits_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_baits',
            name='edible',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Їстівна'),
        ),
    ]
