# Generated by Django 2.2.20 on 2021-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210810_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
