# Generated by Django 2.2.20 on 2021-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210811_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rods',
            name='spacialization',
        ),
    ]
