# Generated by Django 2.2.20 on 2021-08-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_rods_spacialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='owmer',
            new_name='owner',
        ),
    ]
