# Generated by Django 2.2.20 on 2021-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210815_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ganeral_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Загальна ціна'),
        ),
    ]
