# Generated by Django 2.2.20 on 2021-08-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210817_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ganeral_price',
            new_name='general_price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='ganeral_products',
            new_name='general_products',
        ),
    ]
