# Generated by Django 2.2.20 on 2021-08-21 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210818_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=250, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Мобільний номер')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адреса')),
                ('status', models.CharField(choices=[('new', 'Нове замовлення'), ('in_progres', 'Замовлення обробляється'), ('is_ready', 'Замовлення готове'), ('completed', 'Замовлення виконане')], default='new', max_length=100)),
                ('buying', models.CharField(choices=[('self', 'Самовивіз'), ('delivery', 'Доставка')], default='self', max_length=50)),
                ('comment', models.TextField(blank=True, null=True, verbose_name="Коментар до замовлення(не обов'язково)")),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отримання замовлення')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='main.Customer', verbose_name='Покупець')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='main.Order', verbose_name='Замовлення покупця'),
        ),
    ]
