# Generated by Django 4.0.1 on 2022-02-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_alter_categoryfeature_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='value',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='specs.featurevalidator', verbose_name='Значення'),
        ),
    ]
