# Generated by Django 4.0.1 on 2022-02-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_banner_alter_cart_final_price_alter_cart_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
