# Generated by Django 4.0.1 on 2022-02-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
