# Generated by Django 4.0.1 on 2022-02-20 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отримання замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове замовлення'), ('in_progress', 'Замовлення в оброці'), ('is_ready', 'Замовлення готове'), ('completed', 'Замовленння виконане'), ('canceled', 'Замовлення скасовано')], default='new', max_length=100, verbose_name='Статус замовлення'),
        ),
    ]
