# Generated by Django 4.0.1 on 2022-02-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_order_order_date_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
