# Generated by Django 4.0.1 on 2022-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
        migrations.AddField(
            model_name='product',
            name='img8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Додаткове зображення (не обов'язково)"),
        ),
    ]
