# Generated by Django 4.0.1 on 2022-02-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_product_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img1',
            new_name='img',
        ),
    ]
