# Generated by Django 4.0.1 on 2022-02-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_img1_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='img1',
        ),
    ]
