# Generated by Django 4.0.1 on 2022-03-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_banner_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ваше ім'я")),
                ('generalDescription', models.CharField(max_length=255, verbose_name='Коротка оцінка товару')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comment', to='mainapp.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='related_comment', to='mainapp.CommentModel', verbose_name='Коментарі'),
        ),
    ]
