# Generated by Django 4.0.1 on 2022-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_commentmodel_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення'),
        ),
    ]
