# Generated by Django 4.0.1 on 2022-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_product_mainview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Ваш логін')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша електронна пошта')),
                ('newPassword', models.CharField(max_length=255, verbose_name='Новий пароль')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
        ),
    ]
