# Generated by Django 4.0.1 on 2022-04-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_changepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepassword',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
