# Generated by Django 4.0.1 on 2022-04-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_product_comment_alter_commentmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Товар'),
        ),
    ]
