# Generated by Django 4.0.1 on 2022-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_commentmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Товар'),
        ),
    ]
