# Generated by Django 3.2.9 on 2022-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_commentmodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Як до вас звертатись')),
                ('contact', models.CharField(max_length=255, verbose_name="Електронна поошта або номер телефону для зв'язку")),
                ('description', models.TextField(verbose_name='Задайте питання або опишіть проблему')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення')),
            ],
        ),
    ]
