# Generated by Django 3.2.9 on 2022-04-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_supportmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportModel',
            new_name='Support',
        ),
    ]
