# Generated by Django 3.2.9 on 2022-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_rename_supportmodel_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('prosses', 'В процеці'), ('closed', 'Закрито')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
