# Generated by Django 3.2.9 on 2021-12-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20211205_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50, verbose_name="Ім'я ключа для категорії")),
                ('feature_filter_name', models.CharField(max_length=50, verbose_name='Імя для фільтра')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Одинаця виміру')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'unique_together': {('category', 'feature_name', 'feature_filter_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.characteristiccategory', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_feature_value', models.CharField(max_length=100, verbose_name='Валідне значення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
                ('feature_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.characteristiccategory', verbose_name='Ключ характеристики')),
            ],
        ),
    ]
