# Generated by Django 4.0.1 on 2022-01-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211205_1812'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50, verbose_name="Ім'я ключа для категорії")),
                ('feature_filter_name', models.CharField(max_length=50, verbose_name='Імя для фільтра')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Одинаця виміру')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'unique_together': {('category', 'feature_name', 'feature_filter_name')},
            },
        ),
        migrations.CreateModel(
            name='FeatureValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_feature_value', models.CharField(max_length=100, verbose_name='Валідне значення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
                ('feature_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.categoryfeature', verbose_name='Ключ характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.categoryfeature', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
        ),
        migrations.RemoveField(
            model_name='characteristicvalidator',
            name='category',
        ),
        migrations.RemoveField(
            model_name='characteristicvalidator',
            name='feature_key',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='product',
        ),
        migrations.DeleteModel(
            name='CharacteristicCategory',
        ),
        migrations.DeleteModel(
            name='CharacteristicValidator',
        ),
        migrations.DeleteModel(
            name='ProductCharacteristic',
        ),
    ]
